server:
  port: 8084
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  zipkin:
    base-url:http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0