server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
  application:
    name: RATING-SERVICE
  config:
    import: configserver:http://localhost:8086

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8084/eureka

okta:
  oauth2:
    issuer: https://dev-54095434.okta.com/oauth2/default
    audience: api://default